*  datafusion/ERR/2022_005: Private Data Fusion instance has networking permissions.
   - gcpdiag-datafusion1-aaaa/us-central1/my-instance                     [ OK ]

